[workspace]
name = "template-bind-cpp-python"
version = "0.1.0"
description = "C++ Development Environment"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[dependencies]
clang = "==21.1.1"
lld = "==21.1.1"
clang-tools = "==21.1.1"
cppcheck = "==2.18.3"
cmake = "==4.1.1"
ninja = "==1.13.1"
ccache = ">=4.10.0,<5"

[target.linux-64.dependencies]
gcc = "==15.1.0"
gxx = "==15.1.0"
libgcc-ng = "==15.1.0"
libstdcxx-ng = "==15.1.0"

[tasks]
config = "cmake --preset=release"
config-debug = "cmake --preset=debug"
build = "cmake --build build -j 8"
test = "ctest --test-dir build --verbose"
clean = "cmake --build build --target clean"
format = "cmake --build build --target format"
lint = "cmake --build build --target lint"
run-cppcheck = "cmake --build build --target run-cppcheck"
fullcheck = "pixi run lint && pixi run run-cppcheck"
